import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const templates={};
for(const id of ['doorstep','midnight']) templates[id]=await fs.readFile(path.join(root,'chapters',id+'.html'),'utf8');
await fs.writeFile(path.join(root,'assets/templates.js'),'/* Generated by npm run build; edit chapters/*.html instead. */\nwindow.MoonlightTemplates = '+JSON.stringify(templates).replaceAll('<','\\u003c')+';\n');
if(!process.argv.includes('--templates-only')){
  const output=path.join(root,'dist');await fs.rm(output,{recursive:true,force:true});await fs.mkdir(output,{recursive:true});
  const audio=(await fs.readdir(path.join(root,'assets','audio'))).filter(name=>name.endsWith('.mp3')).map(name=>'assets/audio/'+name);
  const files=['index.html','assets/app.css','assets/app.js','assets/storage.js','assets/practice.js','assets/templates.js','assets/lucide.min.js','assets/favicon.svg','chapters/doorstep.css','chapters/doorstep.js','chapters/midnight.css','chapters/midnight.js','licenses/lucide-LICENSE.txt','licenses/voice-assets-NOTICE.md',...audio];
  for(const file of files){await fs.mkdir(path.dirname(path.join(output,file)),{recursive:true});await fs.copyFile(path.join(root,file),path.join(output,file));}
  await fs.writeFile(path.join(output,'.nojekyll'),'');
  console.log('Ready: dist/index.html (all resources are local).');
}else console.log('Chapter templates refreshed.');
